Repository NLog/NLog.Targets.Redis, pull requests merged in 2021-11, with the labels that each got.

#34 Updated to StackExchange.Redis ver. 2.2.4 and added net5.0 platform
  README.md
  appveyor.yml
  src/NLog.Targets.Redis.Tests/Mocks/MockRedisConnectionManager.cs
  src/NLog.Targets.Redis.Tests/Mocks/MockRedisTarget.cs
  src/NLog.Targets.Redis.Tests/NLog.Targets.Redis.Tests.csproj
  src/NLog.Targets.Redis.Tests/RedisConnectionManagerTests.cs
  src/NLog.Targets.Redis.Tests/RedisTargetTests.cs
  src/NLog.Targets.Redis.sln
  src/NLog.Targets.Redis/NLog.Targets.Redis.csproj
  src/NLog.Targets.Redis/RedisConnectionManager.cs
  src/NLog.Targets.Redis/RedisTarget.cs
Labels: size/L

#39 Fix build
  appveyor.yml
Labels: size/XS

#36 Added Sourcelink + Updated changelog
  src/NLog.Targets.Redis/NLog.Targets.Redis.csproj
Labels: size/S

#40 Test project: run .net core 3.1
  src/NLog.Targets.Redis.Tests/NLog.Targets.Redis.Tests.csproj
Labels: size/XS
